### ISSUE TITLE
run generated files through fmt

### ISSUE THREAD

**Issue by naartjie** [dialohq/stork#20]
Any default settings would be better than no formatting. Although a real win would be to check for a local `.ocamlformat` file.

**Comment by wokalski** [comment]
@tsnobip and I considered it when we first built stork. I have mixed feelings about this. I don't think we should encourage people to check in whatever stork generates. On the other hand when you look at the generated code for one reason or another, it'd be nice to have nice formatting there. The only problem this solves that comes to my mind is clarity in the test output in this repo.

**Comment by tsnobip** [comment]
Exactly, stability of snapshots is the biggest benefit
